---
- name: Ensure /etc/bind directory exists
  file:
    path: /etc/bind
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy files to /etc/bind
  copy:
    src: ./roles/docker/files/
    dest: /etc/bind/
    owner: root
    group: root
    mode: '0644'