---
    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        registry: "https://index.docker.io/v1/"

    - name: Pull the private Docker image
      community.docker.docker_image:
        name: cwiara/bind9-image
        tag: latest
        source: pull

    - name: Run the Docker container
      community.docker.docker_container:
        name: bind9
        image: cwiara/bind9-image:latest
        state: started
        restart_policy: always
        published_ports:
          - "53:53/udp"  
          - "53:53/tcp" 