---
    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        registry: "https://index.docker.io/v1/"

    - name: Pull the private Docker image
      community.docker.docker_image:
        name: cwiara/bind9-image
        tag: 1.0.1
        source: pull

    - name: Run the Docker container
      community.docker.docker_container:
        name: bind9
        image: cwiara/bind9-image:1.0.1
        state: started
        restart_policy: always
        published_ports:
          - "53:53/udp"  
          - "53:53/tcp" 
        volumes:
          - /etc/bind/named.conf:/etc/bind/named.conf
          - /etc/bind/named.conf.local:/etc/bind/named.conf.local
          - /etc/bind/named.conf.options:/etc/bind/named.conf.options
          - /etc/bind/zones:/etc/bind/zones

    - name: Restart BIND inside the container
      community.docker.docker_container_exec:
        container: bind9
        command: service named restart