FROM debian:bullseye-slim
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    bind9 \
    bind9utils \
    bind9-doc \
    dnsutils \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 53/udp
EXPOSE 53/tcp

VOLUME /etc/bind

CMD ["named", "-g", "-c", "/etc/bind/named.conf"]
