name: Minikube Workflow

on:
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./minikube/terraform
    env:
        TF_VAR_proxmox_endpoint: ${{ secrets.PROXMOX_ENDPOINT }}
        TF_VAR_proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
        TF_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
        TF_VAR_minikube_password: ${{ secrets.MINIKUBE_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

  review:
    needs: terraform-plan
    runs-on: self-hosted
    environment: 'approve'
    steps:
      - name: Review Terraform Plan
        run: |
          echo "Terraform plan accepted."

  terraform-apply:
    defaults:
      run:
        working-directory: ./minikube/terraform
    needs: review
    runs-on: self-hosted
    outputs:
      vm_ip: ${{ steps.get_vm_ip.outputs.only_IP }}
    env:
        TF_VAR_proxmox_endpoint: ${{ secrets.PROXMOX_ENDPOINT }}
        TF_VAR_proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
        TF_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
        TF_VAR_minikube_password: ${{ secrets.MINIKUBE_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Terraform Output
      id: get_vm_ip 
      run: |
        vm_IP=$(terraform output -raw vm_ip)
        only_IP=${vm_IP%/*}
        echo "only_IP=${only_IP}" >> $GITHUB_OUTPUT

  ansible:
    defaults:
      run:
        working-directory: ./minikube/ansible
    needs: terraform-apply
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.K8S_SSH_PRIVATE_KEY }}" > k8s.key
          chmod 600 k8s.key

      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: minikube
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_PRIVATE_KEY_FILE: ./k8s.key
          vm_IP: ${{ needs.terraform-apply.outputs.vm_ip }}
        run: |
          sleep 30s
          ansible-playbook main.yml -i "$vm_IP," -u $ANSIBLE_USER